### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by davelab6** [rosettatype/Handjet#11]
Please add a nice .gif (drawbot/etc source files) to /docs that shows off the face, and inline it near the top of README

Also, please add 1-3 short paragraphs of description text about the family, which I can use on the fonts.google.com specimen page (you can make a `DESCRIPTION.en_us.html` file directly, if you wish). 

I am curious - what is the meaning and origin of the family name?

**Comment by davelab6** [comment]
@MrBrezina should be quick for you to resolve these 3 points :)

**Comment by MrBrezina** [comment]
@davelab6 let me know if these descriptions (both README and the html) work for you. I will have them proofread later. Also, first animation is up. I wanted to record a screencast with FontGoggles, but that ended up being ca 30MB. I guess, I will just add a single word animated with DrawBot.

**Comment by MrBrezina** [comment]
Done! If you do not love these animations, you are a bad person!
