### ISSUE TITLE
U+2044 FRACTION SLASH does not produce denominator

### ISSUE THREAD

**Issue by dscorbett** [rosettatype/Handjet#12]
In [version 2.000](https://github.com/rosettatype/handjet/blob/2fe545dc7256bbece053a5bf3a33705bb4b3bad5/fonts/Handjet%5BEGRD%2CESHP%2Cwght%5D.ttf), denominators after U+2044 are rendered as numerators. For example, here is <U+0031 DIGIT ONE, U+2044 FRACTION SLASH, U+0032 DIGIT TWO>:
![1⁄2](https://user-images.githubusercontent.com/1124347/94346747-b9aa2b00-fffc-11ea-8a9b-0324b030e385.png)

**Comment by davelab6** [comment]
@kontur will you be able to fix this? :)

**Comment by kontur** [comment]
I'll look into it this week.

**Comment by MrBrezina** [comment]
Thanks. I rewrote the code to build fractions even for combinations like 23/345 (not more than three numerators or denominators).
