### ISSUE TITLE
Missing Arabic positional forms

### ISSUE THREAD

**Issue by dscorbett** [rosettatype/Handjet#13]
In [version 2.000](https://github.com/rosettatype/handjet/blob/2fe545dc7256bbece053a5bf3a33705bb4b3bad5/fonts/Handjet%5BEGRD%2CESHP%2Cwght%5D.ttf), U+066F ARABIC LETTER DOTLESS QAF, U+06BA ARABIC LETTER NOON GHUNNA, and U+06C2 ARABIC LETTER HEH GOAL WITH HAMZA ABOVE are missing their initial and medial forms, and U+0760 ARABIC LETTER FEH WITH TWO DOTS BELOW is missing its initial, medial, and final forms.
![ٯـ ـٯـ ـٯ␤ںـ ـںـ ـں␤ۂـ ـۂـ ـۂ␤ݠـ ـݠـ ـݠ␤](https://user-images.githubusercontent.com/1124347/94444291-2c89e200-0174-11eb-98e1-a99c558a8b03.png)

**Comment by MrBrezina** [comment]
@dscorbett The `U+0760 ARABIC LETTER FEH WITH TWO DOTS BELOW` was a missing code, apologies. Are you sure the others actually get used or you are comparing some glyph sets?

I have added them now, but I wonder if they are really needed.

**Comment by dscorbett** [comment]
I am comparing the font to Unicode’s [ArabicShaping.txt](https://www.unicode.org/Public/13.0.0/ucd/ArabicShaping.txt). I don’t think the other forms are in common modern use. They do exist, though.
