### ISSUE TITLE
U+05BA HEBREW POINT HOLAM HASER FOR VAV is positioned wrong

### ISSUE THREAD

**Issue by dscorbett** [rosettatype/Handjet#15]
When applied to U+05D5 HEBREW LETTER VAV, U+05BA HEBREW POINT HOLAM HASER FOR VAV is positioned identically to U+05B9 HEBREW POINT HOLAM. U+05BA should go above and to the left. (On other letters, U+05B9 goes above and to the left and U+05BA is invalid.)
![וֹוֺ](https://user-images.githubusercontent.com/1124347/94999569-2044c100-0588-11eb-8add-80a1923392f2.png)

**Comment by dscorbett** [comment]
You shifted both U+05B9 and U+05BA to the left instead of just U+05BA. Now U+05B9 HEBREW POINT HOLAM is positioned wrong. The point of having two holam code points is so that <U+05D5, U+05B9> and <U+05D5, U+05BA> look different.
![וֹוֺ](https://user-images.githubusercontent.com/1124347/95122055-f3c2ad80-071d-11eb-9df4-7e09e8943062.png)

**Comment by MrBrezina** [comment]
Ah, I didn’t remember they use the same anchor. Is this acceptable? From right to left:
- <U+FB4B> (precomposed Vav + Holam)
- <U+05D5, U+05B9> (Vav + Holam)
- <U+05D5, U+05BA> (Vav + Holam Haser)

<img width="437" alt="Screenshot 2020-10-06 at 10 03 59" src="https://user-images.githubusercontent.com/485475/95175262-86fdf080-07bb-11eb-9a65-764e171dd458.png">

**Comment by dscorbett** [comment]
Yes, that looks good.
