### ISSUE TITLE
Wrong glyph for U+05C7 HEBREW POINT QAMATS QATAN

### ISSUE THREAD

**Issue by dscorbett** [rosettatype/Handjet#16]
In this font, U+05C7 HEBREW POINT QAMATS QATAN looks identical to U+05B8 HEBREW POINT QAMATS. According to [L2/04-150](http://www.unicode.org/L2/L2004/04150-n2755-qamats-qatan.pdf), U+05C7 “is usually presented with a longer vertical; it can also be represented simply with a larger glyph, and in one case we have found the horizontal lengthened and bent.”

**Comment by MrBrezina** [comment]
@dscorbett thank you for being thorough.
