### ISSUE TITLE
Incomplete soft-dotting

### ISSUE THREAD

**Issue by dscorbett** [rosettatype/Handjet#17]
Soft dots are only removed from ⟨i⟩ and ⟨j⟩. The following should also lose their dots in the same contexts:

* U+012F LATIN SMALL LETTER I WITH OGONEK
* U+0456 CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
* U+0458 CYRILLIC SMALL LETTER JE
* U+1ECB LATIN SMALL LETTER I WITH DOT BELOW

**Comment by MrBrezina** [comment]
Thanks, will fix that. I do not think it makes sense to go any further and allow any arbitrary stack of accents for example.
