### ISSUE TITLE
Decomposed pasekh tsvey yudn is rendered wrong

### ISSUE THREAD

**Issue by dscorbett** [rosettatype/Handjet#19]
The sequence <U+05F2 HEBREW LIGATURE YIDDISH DOUBLE YOD, U+05B7 HEBREW POINT PATAH> should look identical to U+FB1F HEBREW LIGATURE YIDDISH YOD YOD PATAH.
![ײַײַ](https://user-images.githubusercontent.com/1124347/95683197-b182eb80-0bb7-11eb-92d4-7f823cf27058.png)

**Comment by dscorbett** [comment]
This was only partially fixed. It only works when the text is tagged as Yiddish because the relevant lookup uses the language system tag 'JII '.

**Comment by MrBrezina** [comment]
Yes, we wanted it like that. To our knowledge this should not form in Hebrew.

**Comment by dscorbett** [comment]
Because <U+05F2, U+05B7> and U+FB1F are canonically equivalent, they should look equivalent, regardless of language tagging.

**Comment by MrBrezina** [comment]
ah, ok fair point, lemme fix that
