### ISSUE TITLE
macOS rendering weirdness

### ISSUE THREAD

**Issue by davelab6** [rosettatype/Handjet#2]
On Chrome Version 84.0 (latest stable) and macOS 10.14.6 (so not latest 10.15) I see weird rendering up to 106 pt, then at 107 pt it resolves itself. 

<img width="567" alt="Screen Shot 2020-08-04 at 9 29 05 AM" src="https://user-images.githubusercontent.com/261579/89299664-fe38cc00-d634-11ea-9ffe-a10d724cef28.png">
<img width="558" alt="Screen Shot 2020-08-04 at 9 29 16 AM" src="https://user-images.githubusercontent.com/261579/89299665-fed16280-d634-11ea-8859-35a58d521a2c.png">

**Comment by davelab6** [comment]
Glitch on SHAP axis @ 150 and size @ 64, but not at 65:

<img width="1045" alt="Screen Shot 2020-08-04 at 11 09 33 AM" src="https://user-images.githubusercontent.com/261579/89310702-0ef03e80-d643-11ea-9ed1-bbd8ccf0fe2e.png">

<img width="1008" alt="Screen Shot 2020-08-04 at 11 09 38 AM" src="https://user-images.githubusercontent.com/261579/89310701-0e57a800-d643-11ea-9602-6958ed3f2ca0.png">

**Comment by MrBrezina** [comment]
I have no idea how to resolve this or even bug track it. My inclination here is to wash my hands and say it is the browser’s fault.

**Comment by davelab6** [comment]
Agreed. Happens in Safari too, so I've reported it at https://feedbackassistant.apple.com :)

**Comment by kontur** [comment]
Concur. May guess is that the renderer fails to recognize the pixel components being nearly or entirely on top of each other. The lower the EGRD value the more likely it seems to glitch. 

If we can do nothing about the glitch I am wondering if this warrants setting the default EGRD value to 2 instead — or is this too much of a concession to a bug? I guess we all agree the "single" element would be the nicer default?

**Comment by MrBrezina** [comment]
Single element for me please. But as long as it is a square, I am flexible.

**Comment by davelab6** [comment]
+1 to single element, Apple users upgrade pretty quickly so I'm OK with this. If it happened in MS Word, may be a tougher decision :)
