### ISSUE TITLE
Decomposing Yiddish digraphs makes them wider

### ISSUE THREAD

**Issue by dscorbett** [rosettatype/Handjet#20]
The Yiddish digraphs U+05F0..U+05F2 are decomposed. The digraph glyphs (`hbVav_hbVav` etc.) are narrower than the pairs they are decomposed into (`hbVav hbVav` etc.). For U+05F0 and U+05F1, this is harmless though pointless, but it makes a vowelless U+05F2 HEBREW LIGATURE YIDDISH DOUBLE YOD wider than it is with patah, which may have been unintentional. Here is <U+05F2, U+05F2, U+05B7>:
![ײײַ](https://user-images.githubusercontent.com/1124347/96054638-0e98ce80-0e50-11eb-8341-e7a6f114e445.png)

I recommend not decomposing U+05F0..U+05F2.

**Comment by MrBrezina** [comment]
This is a problem with kerning which I have now resolved. When I decomposed to `hbYod hbYod hbPatah` the mark ended up shifted under the first letter for some reason (despite the sequence being correct) which got me confused. Now, I decompose all precomposed ligatures and compose them back only when `liga` feature is active and `hbYod_hbYod_hbPatah` ligature is composed only when Yiddish is set as a language.
