### ISSUE TITLE
Combinations of shaddah and other marks are spacing

### ISSUE THREAD

**Issue by dscorbett** [rosettatype/Handjet#21]
Some combinations of U+0651 ARABIC SHADDA with other marks are ligated into spacing glyphs. They should not be spacing. For example, here is <U+06CC ARABIC LETTER FARSI YEH, U+064D ARABIC KASRATAN, U+0651 ARABIC SHADDA>:
![یٍّ](https://user-images.githubusercontent.com/1124347/96055861-2de52b00-0e53-11eb-9381-edf50f8d81e1.png)

The glyphs for U+FC5E..U+FC63 should still be spacing.

**Comment by MrBrezina** [comment]
Oops there must be an encoding issue.

Is there any chance you could provide all issues collectively and not one by one?

**Comment by dscorbett** [comment]
Okay.

**Comment by MrBrezina** [comment]
Thank you. Just to be clear, I do not mind individual issues. That is great. I would just prefer to fix as many of the issues as possible in a single run. I understand that new issues might occur as a result of fixing of others.
