### ISSUE TITLE
let's try with flattening nested component

### ISSUE THREAD

**Issue by RosaWagner** [rosettatype/Handjet#22]
It's been a while that fontmake has the `--flatten-components` argument which flatten the nested components, and we think it may fix the rendering issue in MacOS. @kontur do you think you can add it to the build script, so I can re-ship the font and check it in GF sandbox if it displays better ?

**Comment by RosaWagner** [comment]
I don't think it will fix it totally cause maybe the overlapping components are more problematic than the nested ones, but we can try.

**Comment by kontur** [comment]
Sorry, what's the context for this? Or are you just generally suggesting we should add that?

**Comment by RosaWagner** [comment]
Sorry, the context is that handjet is blocked in GF sandbox because of the rendering issue on Mac (and also cause the custom axes are still not registered cf. https://github.com/google/fonts/issues/3817), and I am reviewing the blocked projects and try to unblock them. It would be interesting to see if removing the nested components can somehow improve something or not.

**Comment by MrBrezina** [comment]
I don’t think there are nested components anymore. There is just a single component which contains contours and that component is used to build other glyphs.

**Comment by kontur** [comment]
Easy enough to test, will update this week @RosaWagner .

@MrBrezina The flatten components thing refers to components that have components, e.g. `Ä` with `dieresiscomb`, which in turn has the `pixel` component, thus being nested more than one level deep, which can cause buggyish behaviour in some instances.

**Comment by kontur** [comment]
@RosaWagner see https://github.com/rosettatype/handjet/tree/flatten-components — file size increased approx x2, but rendering is imo the same when compared to the previous version (left previous commit, right with `--flatten-components`). The [comparison file](https://github.com/rosettatype/handjet/blob/flatten-components/test/flatten-comparison.html) is in the repo as well. Hard to say if [rendering improved or not](https://github.com/rosettatype/handjet/issues/2) in recent Mac OS updates, but the glitching is the same in latest Safari, Chrome and Firefox.

![handjet-flatten-components-comparison](https://user-images.githubusercontent.com/1893577/154995508-7590fca6-d16e-4295-8405-9d82857d5754.png)

**Comment by RosaWagner** [comment]
Ok, well now we know. Thanks for testing this :) Better to preserve file size if the rendering is the same.

**Comment by kontur** [comment]
Roger. The rendering is a bit of a tricky call... at the display sizes the font is designed for the glitches are minimal or non-existant, but the smaller and bolder it goes the more we seem at the mercy of the rendering engine. Decomposing all glyphs in this font would be madness in terms of file size, so I'm somewhat clueless what to suggest or even where to raise this issue.

**Comment by davelab6** [comment]
Curiously it doesn't seem to occur on https://rosettatype.com/Handjet at the moment! Is the VF file used on that page the same as the latest one on this repo?

**Comment by MrBrezina** [comment]
Yes, pretty much. Just a different family and file names.
