### ISSUE TITLE
Axes tag modification

### ISSUE THREAD

**Issue by RosaWagner** [rosettatype/Handjet#23]
Hi @kontur @MrBrezina 

We are in process of registering the axes to onboard the complete VF.

At GF they decided on making the axes tag a bit clearer: Element shape would become ELSP (instead of ESHP), and Element grid would become ELGR (instead of EGRD).

**Comment by MrBrezina** [comment]
Hi @RosaWagner 

Thanks for the heads up. It would be great if GF  consulted that change with us beforehand. I have already changed it once after GF’s (Dave’s) suggestions. This will break things for people who are already using the fonts (if they update ofc.).

To be frank, I don’t understand the logic. If you insist on two letters for the element, which limits your options for describing the variations on the element to the two letters that are left, why not apply the same to the shape, i.e. *SH*ape would be better than *S*ha*P*e?

**Comment by RosaWagner** [comment]
I don’t know David, they discuss these stuff internally for the axes to apply to any font which would support these axes. Don’t touch anything for now, I will give your feedback and come back to you with an answer.

**Comment by kontur** [comment]
_Imo_ the all caps axes names already denote non-standardized axes, no? It seems unnecessary to impose _more_ changes regarding those for contributing projects; particularly when there is no clear improvement or logic.

**Comment by RosaWagner** [comment]
To be clear, what we call axis registration has nothing to do with Miscrosoft; it is the process of implementing an axis in the API so it can display the sliders and automatically generates statics fallbacks.

The problem on GF side, is that they are registering dozens of axes, and some start with a E; they need to be able to differentiate Element from Extrusion, Edge etc. If we have for example Extrusion Shape and Element Shape, they can't be both called ESPH. We have like 20 VF to onboard requiring GF to implement custom axes in their API, and we are trying to make it all work. They also need to anticipate new potential axes and so trying to find a system (which is already compromised by the axes they registered in the past). 

This was just to give you more context on the problem, but they are still debating.

**Comment by kontur** [comment]
Hey @RosaWagner thanks for the context, appreciate the additional info. To be frank this sounds like an UI implementation issue being off-loaded onto contributing open source font repositories. All (arbitrary) axes are unique within the specific font tester, so it is hard to understand why or how those need to be standardized on a library-level. We'll hang back until we hear from you :)

**Comment by RosaWagner** [comment]
Hi, they finally stated (after considering also ELSH or ELSP), and they decided to remain on **ELSH** and **ELGR**.

@kontur you are right it is a UI issue, but there is no much ways to go with it. The system is made in a way that we can have the same tag for two different axes, it would break the API. Mistakes were made, and they can't be fixed now that there are several billions of users. The last mistake was to go without thinking of the other projects hanging in the pipeline because of time pressure. But that is how requirements are built over time. We do have to think of multiple font projects, with multiple axes, led by multiple designers and make it all work with some kind of consistency (despite the mistake already done, and being blind about the future). I am truly sorry that individual designers have to compromise because of that.

**3 solutions:** 
1. The font is updated here (breaking current users' website if they download the new version)
2. A tag rename to export 2 families could be integrated in your build (confusing for the users but not breaking stuff)
3. GF makes a fork so it complies with GF API spec (annoying to maintain and confusing for users, plus redirects users to a fork).

For each proposal you can ask "How many users would that be?" and "How much work would that represent?" and see what  would be the best compromise :)

**Comment by kontur** [comment]
Thanks @RosaWagner for the detailed insight. The reasoning is sound, it’s just the _decreed upon nature_ of this request that dampens the mood. The axes names are now updated in `master`.

**Comment by RosaWagner** [comment]
I understand. Thanks for making the changes, really appreciated.
