### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [rosettatype/Handjet#28]
.

**Comment by kenmcd** [comment]
Seems to work in ID17.

![Windows 11 Tests-2024-01-13-15-45-14](https://github.com/rosettatype/handjet/assets/844920/630cf347-5bcc-4d0f-bc98-9d6bb9d1dc89)

But the Min/Max does not seem to work.
Grid should only be a `1` or a `2`.
Shape should be integers from `1` to `16`.
Shape `0` shows nothing.

My test in ID17 displayed all the shapes and the grid seemed to work.

**Comment by curya** [comment]
@kenmcd It doesn't work in Photoshop and Illustrator.

**Comment by MrBrezina** [comment]
Thank you for reporting this here. It is an issue in Adobe software. I have reported it to them a while back and it seems they now have it fixed, but it has not been deployed, yet. I will post here when it is.

Just to be clear:

> Shape 0 shows nothing.

This is intended behaviour, so you can animate from nothing to triangles (Shape = 1).

**Comment by MrBrezina** [comment]
This seems to have been resolved and Handjet works again in InDesign 2024 (19.2), Photoshop 2024 (25.5.1), and Illustrator 2024 (28.3).
