### ISSUE TITLE
Recalibrate GRID

### ISSUE THREAD

**Issue by davelab6** [rosettatype/Handjet#5]
Currently GRID's range of 10..100 and key values of 10, 50, 100 doesn't make sense to me. 

I propose to recalibrate this as 1..3 with -2 levels of precision (as described in https://github.com/google/fonts/tree/master/axisregistry) so that the value of the axis at `1.00` gives 1 grid, element `2.00` gives 2x2, and `3.00` gives 3x3. 

Alternatives I thought about are 

* 1..9 for the total number of elements - but I think int values that map meaningfully, and minimizing the in-between space

* 1, 50, 100 as a kind of percent

<img width="672" alt="Screen Shot 2020-08-04 at 10 17 57 AM" src="https://user-images.githubusercontent.com/261579/89304771-d7ca5f00-d63b-11ea-85a9-06b8707e13c1.png">

<img width="672" alt="Screen Shot 2020-08-04 at 10 17 46 AM" src="https://user-images.githubusercontent.com/261579/89304769-d7ca5f00-d63b-11ea-966b-cf159165b005.png">

<img width="672" alt="Screen Shot 2020-08-04 at 10 17 16 AM" src="https://user-images.githubusercontent.com/261579/89304768-d731c880-d63b-11ea-8b30-2817b29197ca.png">

**Comment by MrBrezina** [comment]
See your point and can do that. It was originally `opsz` axis. I like 1, 2, 3. The values in between are not entirely meaningful and the other options might suggest that.

**Comment by davelab6** [comment]
Great!

**Comment by davelab6** [comment]
`opsz` is interesting - what values would you use?

**Comment by davelab6** [comment]
Perhaps similar to #3 this could be named more specific, `Dot Grid (DOTG)`

**Comment by MrBrezina** [comment]
To answer the previous question. I have used the 10, 50, and 100. Maybe it should have been 10, 20, and 30. But it really is better as an independent axis. Some software uses `opsz` automatically and the number of elements in per stroke should be a users’ decision (it acts as `opsz` only in certain environments).

Re the second, I think `GRID` is great and clear. If you insist on specificity, let’s use `EGRD` (Element grid).

**Comment by davelab6** [comment]
Agreed, no opsz for this. 

So, you will go with `Element Grid (EGRD)` and `Element Shape (ESHP)`?

**Comment by MrBrezina** [comment]
All right

**Comment by davelab6** [comment]
@MrBrezina ETA? :)

**Comment by MrBrezina** [comment]
Are you done with the comments? I want to have all the input ready before we move ahead. If so, we can have it ready in the second half of September. Probably earlier.

Are we settled on the instances in #3 ?

**Comment by kontur** [comment]
Implemented the axis name changes and respective updates to STAT instance names.

**Comment by davelab6** [comment]
This was is done, thank you @kontur :)
